Stage 2
moflotas/iu-big-data-final-proj pull request #2
Opened 2024-04-14 23:40 UTC by markovav-official

2024-04-21 07:13 UTC, moflotas requested changes
Almost fine, but some questions should be discussed

2024-04-21 07:13 UTC, moflotas commented on output/q2.jpg
are there all states at the bottom?
also, where is manual on the graph?

2024-04-21 07:13 UTC, moflotas commented on output/q3.jpg
maybe `distribution`, not `counts`?

2024-04-21 07:13 UTC, moflotas commented on output/q5.jpg
I believe you cannot call it correlation.
Better `Graph of condition dependence on odomoter`

2024-04-21 07:13 UTC, moflotas commented on scripts/stage2.sh
> +beeline -u jdbc:hive2://hadoop-03.uni.innopolis.ru:10001 -n team21 -p $PASSWORD -f sql/q5.hql --hiveconf hive.resultset.use.unique.column.names=false > output/q5.csv 2> /dev/null
extract to a function, no?)

2024-04-21 07:13 UTC, moflotas commented on sql/create_tables.sql
> +    state VARCHAR(255),
now, when the data is preprocessed, we can use `VARCHAR(2)` for state
```suggestion
    state VARCHAR(2),
```

2024-04-21 07:13 UTC, moflotas commented on sql/q1.hql
> +  AND color != '—'
where should we made the conversion of `-` to `NULL`?

2024-04-26 12:00 UTC, moflotas approved these changes
Cool

2024-04-26 17:28 UTC, Nertsal approved these changes

2024-04-27 08:04 UTC, merged